"use client";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, X, CheckCircle2, Share2 } from "lucide-react";

export function ReportViewerModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4 animate-in fade-in">
      <Card className="w-full max-w-4xl max-h-[90vh] glass-panel border-primary/40 shadow-2xl flex flex-col overflow-hidden relative">
        <CardHeader className="flex flex-row items-center justify-between pb-3 border-b border-border/50 shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/20 text-primary">
              <FileText className="h-5 w-5" />
            </div>
            <div>
              <CardTitle className="text-base font-bold">Comprehensive Research Report</CardTitle>
              <p className="text-xs text-muted-foreground">Generated by Report Composer Engine • ARA v1.0</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="gap-1 text-xs">
              <Download className="h-3.5 w-3.5" /> Export PDF
            </Button>
            <Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8 rounded-full">
              <X className="h-4 w-4" />
            </Button>
          </div>
        </CardHeader>

        <CardContent className="flex-1 overflow-y-auto p-6 space-y-6 text-xs text-foreground leading-relaxed">
          {/* Executive Summary */}
          <div className="space-y-2 border-b border-border/40 pb-4">
            <Badge variant="success">Executive Summary</Badge>
            <h2 className="text-lg font-bold text-foreground">
              Comparative Analysis of CRISPR-Cas9 vs Cas12a Off-Target Gene Editing Specificity
            </h2>
            <p className="text-muted-foreground">
              This synthesis aggregates 42 academic literature references across PubMed, BioRxiv, and Nature Genetics.
              Multi-agent reasoning identified 3 major contradiction claims between early cell-line assays and recent primary human T-cell experiments.
            </p>
          </div>

          {/* Section 1 */}
          <div className="space-y-2">
            <h3 className="text-sm font-semibold text-primary">1. Off-Target Mutational Frequencies</h3>
            <p>
              Cas12a (Cpf1) exhibits significantly lower off-target cleavage frequencies (0.02%) compared to canonical SpCas9 (0.45%) across non-repetitive genomic loci. High-throughput Digenome-seq data indicates that Cas12a requiring a 5&apos;-TTTN-3&apos; PAM site restricts potential off-target binding candidates.
            </p>
          </div>

          {/* Section 2 */}
          <div className="space-y-2">
            <h3 className="text-sm font-semibold text-primary">2. Resolved Contradiction Audit</h3>
            <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 space-y-1">
              <span className="font-semibold text-amber-300">Contradiction Claim #1:</span>
              <p className="text-muted-foreground">
                Study A reported 12% off-target cleavage in HEK293 cells for Cas9, whereas Study B reported &lt;0.1% off-target cleavage.
                <strong> Resolution:</strong> Discrepancy caused by gRNA length truncation (20nt vs 18nt sgRNA).
              </p>
            </div>
          </div>

          {/* Citation References */}
          <div className="pt-4 border-t border-border/40 space-y-2 text-[11px] text-muted-foreground">
            <span className="font-semibold text-foreground">Verified References:</span>
            <ol className="list-decimal list-inside space-y-1">
              <li>Zetsche et al., Cpf1 is a single RNA-guided endonuclease. Cell 2015.</li>
              <li>Kleinstiver et al., Genome-wide specificities of CRISPR-CasCpf1 nucleases. Nat Biotechnol 2016.</li>
            </ol>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
