"""Error Code enumerations for the Core Foundation."""

from enum import Enum, unique


@unique
class ErrorCode(Enum):
    """Standardized error codes across the core foundation."""

    # General & System
    UNKNOWN_ERROR = "ERR_UNKNOWN"
    INVALID_REQUEST = "ERR_INVALID_REQUEST"
    VALIDATION_ERROR = "ERR_VALIDATION_FAILED"

    # Session Management
    SESSION_NOT_FOUND = "ERR_SESSION_NOT_FOUND"
    SESSION_ALREADY_EXISTS = "ERR_SESSION_ALREADY_EXISTS"
    SESSION_STATE_INVALID = "ERR_SESSION_STATE_INVALID"
    SESSION_EXECUTION_FAILED = "ERR_SESSION_EXECUTION_FAILED"

    # Registry & Capabilities
    CAPABILITY_NOT_FOUND = "ERR_CAPABILITY_NOT_FOUND"
    CAPABILITY_ALREADY_REGISTERED = "ERR_CAPABILITY_ALREADY_REGISTERED"
    CAPABILITY_INVALID = "ERR_CAPABILITY_INVALID"

    # Routing
    ROUTING_FAILED = "ERR_ROUTING_FAILED"
    NO_SUITABLE_TOOL = "ERR_NO_SUITABLE_TOOL"

    # Event Bus
    EVENT_DISPATCH_FAILED = "ERR_EVENT_DISPATCH_FAILED"
    SUBSCRIBER_ERROR = "ERR_SUBSCRIBER_ERROR"

    # Configuration
    CONFIG_NOT_FOUND = "ERR_CONFIG_NOT_FOUND"
    CONFIG_INVALID = "ERR_CONFIG_INVALID"

    # Dependency Injection
    DEPENDENCY_NOT_FOUND = "ERR_DEPENDENCY_NOT_FOUND"
    DEPENDENCY_RESOLUTION_FAILED = "ERR_DEPENDENCY_RESOLUTION_FAILED"
    DEPENDENCY_ALREADY_REGISTERED = "ERR_DEPENDENCY_ALREADY_REGISTERED"
