"use client";

import React from "react";
import { useDataStore } from "@/store/use-data-store";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Sparkles, Download, AlertTriangle, ShieldCheck } from "lucide-react";
import { useUIStore } from "@/store/use-ui-store";

export function AIDataAnalyst() {
  const { aiInsights, selectedDataset, datasets } = useDataStore();
  const { addToast } = useUIStore();
  const dataset = selectedDataset || datasets[0];

  const handleExportReport = () => {
    const reportContent = `# Data Intelligence Analysis Report: ${dataset.name}\n\n${aiInsights}\n\n---\n*Generated by ARA AI Data Analyst*`;
    const blob = new Blob([reportContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Data_Analysis_${dataset.name}.md`;
    a.click();
    addToast({ type: "success", title: "Report Exported", message: "Downloaded Markdown analytics report." });
  };

  return (
    <Card variant="glass" className="space-y-4">
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-indigo-400" />
            AI Statistical Analyst & Anomaly Detection
          </CardTitle>
          <CardDescription>Automated statistical summaries and outlier isolation</CardDescription>
        </div>

        <Button variant="outline" size="sm" onClick={handleExportReport} leftIcon={<Download className="w-4 h-4" />}>
          Export Analysis Report
        </Button>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* Anomaly Callout Banner */}
        {dataset.anomalies_detected > 0 && (
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
            <div>
              <h4 className="text-xs font-bold text-amber-300">
                {dataset.anomalies_detected} Outlier Anomalies Isolated
              </h4>
              <p className="text-xs text-slate-300 mt-0.5 leading-relaxed">
                Elevated off-target rates (&gt; 0.40) detected in VEGFA locus. Automated filtering applied.
              </p>
            </div>
          </div>
        )}

        {/* AI Insight Markdown Render */}
        <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 text-xs font-mono text-slate-200 leading-relaxed whitespace-pre-wrap">
          {aiInsights}
        </div>
      </CardContent>
    </Card>
  );
}
