"""Core Workflow Package — Autonomous Research Workflow Engine (ARA Version 3.0)."""

from core.workflow.engine import AutonomousResearchEngine
from core.workflow.integration import (
    CollaborationWorkflowIntegration,
    DataWorkflowIntegration,
    KnowledgeWorkflowIntegration,
    LearningWorkflowIntegration,
    PlannerWorkflowIntegration,
    ReflectionWorkflowIntegration,
)
from core.workflow.models import (
    CitationRecord,
    CitationStyle,
    ConflictReport,
    ConflictSeverity,
    ConstraintSpec,
    EvidenceConfidence,
    EvidenceRecord,
    EvidenceSourceType,
    GoalDomain,
    GoalPriority,
    QuestionPriority,
    QuestionStatus,
    ReportFormat,
    ReportSection,
    ResearchGoal,
    ResearchQuestion,
    ResearchReport,
    ResearchWorkflowContext,
    ResolutionAction,
    WorkflowMetrics,
    WorkflowStage,
    WorkflowStatus,
)

__all__ = [
    "AutonomousResearchEngine",
    "ResearchGoal",
    "GoalDomain",
    "GoalPriority",
    "ConstraintSpec",
    "ResearchQuestion",
    "QuestionPriority",
    "QuestionStatus",
    "EvidenceRecord",
    "EvidenceSourceType",
    "EvidenceConfidence",
    "ConflictReport",
    "ConflictSeverity",
    "ResolutionAction",
    "CitationRecord",
    "CitationStyle",
    "ResearchReport",
    "ReportSection",
    "ReportFormat",
    "ResearchWorkflowContext",
    "WorkflowStage",
    "WorkflowStatus",
    "WorkflowMetrics",
    "PlannerWorkflowIntegration",
    "CollaborationWorkflowIntegration",
    "KnowledgeWorkflowIntegration",
    "ReflectionWorkflowIntegration",
    "LearningWorkflowIntegration",
    "DataWorkflowIntegration",
]
